### ISSUE TITLE
parseSource: move semantic analysis into the if branched

### ISSUE THREAD

**Issue by MarcusDenker** [myroslavarm/Experimental-Completion#2]
parseSource:

- a special doSemanticAnalysisIn: was added for RBProgramNode and the existing guarded for nil... but we could just instead use  doSemanticAnalysis when the class is nil. Much simpler.

**Comment by myroslavarm** [comment]
fixed with this commit:
https://github.com/myroslavarm/Experimental-Completion/pull/1/commits/3df46275bbcd5235f1526e392e8cab7525761c78
