### ISSUE TITLE
add test: 1 + (1 si

### ISSUE THREAD

**Issue by MarcusDenker** [myroslavarm/Experimental-Completion#23]
in the old completion, we get a suggestion for the send.

With the new one, we do not as the parser parses all the faulty code in one parse error node.

First step: add two tests (one for old, one for now) so we do not forget.

**Comment by myroslavarm** [comment]
done : https://github.com/myroslavarm/Experimental-Completion/commit/2904350849acd5ae1bda1e1a318df1946e2bfa14
