### ISSUE TITLE
Pharo8: make a PR to remove the OCompletion  classes

### ISSUE THREAD

**Issue by MarcusDenker** [myroslavarm/Experimental-Completion#24]
Ocompletion is about sorting results. We will add an API for that later.

For now everything would be simpler if we could remove the dedicated OCompletion code
(Controller and all the classes in the category)

**Comment by MarcusDenker** [comment]
I added am Issue on the Pharo issue tracker: https://github.com/pharo-project/pharo/issues/3614

**Comment by myroslavarm** [comment]
done and implemented : https://github.com/pharo-project/pharo/pull/3643
