### ISSUE TITLE
Pharo8: Make a minimal PR with just the code needed for CompletionController

### ISSUE THREAD

**Issue by MarcusDenker** [myroslavarm/Experimental-Completion#26]
It would be nice if we could add CompletionController already to the image and have people testing it.

it does not need much: CompletionController, CompletionContext, TypingVisitor what else?

The good thing would be that we could test it for real (even make it default for a while)

This could be added to the NECompletion package (in its own Tag, like OCompletion now)

**Comment by myroslavarm** [comment]
done : https://github.com/pharo-project/pharo/pull/3665
