### ISSUE TITLE
NewSubContextTest needs to override #shouldInheritSelectors on the class side

### ISSUE THREAD

**Issue by MarcusDenker** [myroslavarm/Experimental-Completion#33]
If we add a method to the class side:

shouldInheritSelectors
	^true

we then can override single tests in the subclass and it will run all tests (non-overriden inherited)

**Comment by myroslavarm** [comment]
done! - https://github.com/myroslavarm/Experimental-Completion/commit/77af9436c110cf4b81c1c038de284948d2999b07
