### ISSUE TITLE
New Model: it is a bit slow

### ISSUE THREAD

**Issue by MarcusDenker** [myroslavarm/Experimental-Completion#36]
It feels a bit slow. 

The reason: we #entries is called a lot. In the old Model it was an instance variable 

we should refactor it to be that.

-> lazy init
-> update on narrowWith:

Something like that...

**Comment by myroslavarm** [comment]
seems to be that the mode complex the node, the slower it is : to check

**Comment by myroslavarm** [comment]
fixed in : https://github.com/myroslavarm/Experimental-Completion/commit/3a8a22fd87d675870fd8c545afb96a8ddc6c2a91
