### ISSUE TITLE
New Model: complete method name

### ISSUE THREAD

**Issue by MarcusDenker** [myroslavarm/Experimental-Completion#38]
when writing the selector at the start, what does the old show as possible completion?

**Comment by myroslavarm** [comment]
so the old completion shows all possible method names both in editor and in playground. it seems i was able to fix it just in the editor (not sure what to do for playground) here : https://github.com/myroslavarm/Experimental-Completion/commit/f1ebda130dbd5831dcb6d7e5eb30ccc278393193

TASK : find out how to do that in playground

**Comment by myroslavarm** [comment]
fixed in : https://github.com/myroslavarm/Experimental-Completion/commit/ec364cb1ba057bad09b45d436d55222ad49ed751 (could be reversed if doesn't make sense)
