### ISSUE TITLE
New Model: we use NECGlobalEntry, instead we should implement our own

### ISSUE THREAD

**Issue by MarcusDenker** [myroslavarm/Experimental-Completion#46]
The CompletionModel uses only one kind of entry from the old system: the NECGlobalEntry

We should instead use our own entry class

**Comment by MarcusDenker** [comment]
We could use the idea to make an empty class and implement everything needed if there is a DNU

**Comment by myroslavarm** [comment]
PR: https://github.com/myroslavarm/Experimental-Completion/pull/56. Already works but there's space for improvements (i.e. making temps display first)

**Comment by myroslavarm** [comment]
implemented
