### ISSUE TITLE
Pharo8 : improve code completion for temps

### ISSUE THREAD

**Issue by myroslavarm** [myroslavarm/Experimental-Completion#49]
when declaring temps, they get completed. they shouldn't because we are essentially making up new variables

**Comment by MarcusDenker** [comment]
is this still a problem in Pharo8? When I tried it did not complete them anymore

**Comment by MarcusDenker** [comment]
double check: the *old* completion wants to complete temp var declarations, the *new* one does not.

Which I think is better.

**Comment by myroslavarm** [comment]
update : 
test completion works well
new model should be fixed

**Comment by myroslavarm** [comment]
should be fixed in : https://github.com/myroslavarm/Experimental-Completion/commit/b1e5b306fb54a4838c245a3463b0056c92f6fa98.
the problem was that because of caching method suggestions and interpreting temp declaration as part of the method, the only suggestion for temps was the name of the class it's in. i have now changed it to no completion, because a) it was totally incorrect b) temp declaration should not be completed

**Comment by MarcusDenker** [comment]
It is now disabled, but it might be interesting later to find a way to suggest something |forThis |

(future work)

**Comment by MarcusDenker** [comment]
this is fixed

**Comment by myroslavarm** [comment]
FINALLY fixed in this commit : https://github.com/pharo-project/pharo/pull/4062/commits/ddc49cdf2ae398da1e2711cecde3625c4ba0e4a8. temps don't get completed but methods do, and everything works! again, the problem was with error node
