### ISSUE TITLE
Pharo8 : completion for "" comments

### ISSUE THREAD

**Issue by myroslavarm** [myroslavarm/Experimental-Completion#50]
right now they get completed. we need to decide if it's good or not, and if not how to fix it

**Comment by myroslavarm** [comment]
e.g.
node isSequence ifTrue: [ ^NECEmptyModel new ].
would fix the comment problem when it is part of the sequence.

**Comment by MarcusDenker** [comment]
we could add a test method to RBProgramNode that returns true if a position in the text is in a comment.
It seems we have all the information available (comments know their start/stop position):

(Object>>#halt) ast comments anySatisfy:  [ :each | each intersectsInterval: (20 to:20)]

**Comment by myroslavarm** [comment]
what would be an example case for a "" comment not being part of the sequence? because i've been testing various cases just now, and it seems that the empty model for sequence takes care of everything

**Comment by MarcusDenker** [comment]
something like

1 + 2 "comment here".

**Comment by MarcusDenker** [comment]
ah, the fun thing: the OLD (NECController) gives a completion here, ours does not! :-)

So yes, this seems to be fixed!

**Comment by myroslavarm** [comment]
already fixed
