### ISSUE TITLE
Pharo8: return empty model for sequence

### ISSUE THREAD

**Issue by MarcusDenker** [myroslavarm/Experimental-Completion#53]
We check for a number of nodes that we are not intersted in in #createModel. We should add
the sequenceNode, too:

node isSequence ifTrue: [ ^NECEmptyModel new ].

**Comment by myroslavarm** [comment]
pull request : https://github.com/pharo-project/pharo/pull/3823

**Comment by MarcusDenker** [comment]
merged!
