### ISSUE TITLE
Pharo8: when writing a selector and there is a block after, we get no completion

### ISSUE THREAD

**Issue by MarcusDenker** [myroslavarm/Experimental-Completion#55]
This example:

self environment allBehaviors 
		select:  [ :class | class slots anySa [ :slot | slot class == self ]].
		

when writing anySa... the old Code Completion suggests selectors. The new we get nothing.

This has something to do with the parse error node later, we need to explore how this is parsed.

**Comment by MarcusDenker** [comment]
What to do: 
- parse the code with the RBParser, look at what the AST looks like at the anySa point.
- is it possible to write a test for this?

**Comment by MarcusDenker** [comment]
Still a problem with the latest code.

**Comment by myroslavarm** [comment]
it seems to parse everything except for methodname as one big sequence node. on the other hand, we have incorrect syntax before the block so this issue is essentially on hold until we are able to complete parse error nodes essentially. but then again, getting a sequence node AST puzzles me

**Comment by MarcusDenker** [comment]
with the fallback this is ok for now
