### ISSUE TITLE
add method definition competion

### ISSUE THREAD

**Issue by myroslavarm** [myroslavarm/Experimental-Completion#60]
the line
(self methodNames includes: aRBMethodNode) ifFalse:  [ ^#() ].
in MatchedNodeProducer >> visitMethodNode: aRBMethodNode 
gets rid of the incorrect temp definition completion, but also stops method definitions from being completed. we need to figure out a way to fix it

**Comment by MarcusDenker** [comment]
This is closed: method definitions are now completed. The workaround stays for not completing temp definitions, which does not work yet

**Comment by myroslavarm** [comment]
reopened because while the workaround exists method definitions are not completed :(

**Comment by myroslavarm** [comment]
fixed in this commit : https://github.com/pharo-project/pharo/pull/4062/commits/ddc49cdf2ae398da1e2711cecde3625c4ba0e4a8
