### ISSUE TITLE
TestCompletionModel: clazz is UndefinedObject by default

### ISSUE THREAD

**Issue by MarcusDenker** [myroslavarm/Experimental-Completion#70]
I wonder if using UndefinedObject is really good. e.g. this means we can not destinguish
"we look at UndefinedObject" vs. really having no class set (in the playground).

Can it not just be nil in the case there is no class?

**Comment by myroslavarm** [comment]
in order to do that, the first thing that needs to be done is to fix visitVariableNode: as it relies heavily on the currentClass implementation which in the case of nil will give errors

**Comment by myroslavarm** [comment]
PR : https://github.com/pharo-project/pharo/pull/4166

**Comment by myroslavarm** [comment]
merged
