### ISSUE TITLE
Setting: navigation keys for extended completion functionality 

### ISSUE THREAD

**Issue by MarcusDenker** [myroslavarm/Experimental-Completion#71]
There is a (right now disable) setting 

Use navigation keys for extended completion functionality

if turned on, one gets with -> (right arrow) a preview of all the code for the possible methods.

==> turn it on and implement the missing methods.

**Comment by MarcusDenker** [comment]
I added all methods to not get a DNU: https://github.com/pharo-project/pharo/pull/4935

**Comment by myroslavarm** [comment]
reminder for self: this still needs to be improved

**Comment by MarcusDenker** [comment]
https://github.com/pharo-project/pharo/pull/5220

with this most of it works

**Comment by MarcusDenker** [comment]
this can be closed
