### ISSUE TITLE
Code completion error regarding Arrays

### ISSUE THREAD

**Issue by MarcusDenker** [myroslavarm/Experimental-Completion#75]
see https://github.com/pharo-project/pharo/issues/4137

**Comment by myroslavarm** [comment]
yes, Cyril sent it to me. of course, a workaround for the DNU on array node is easy but the error is more serious. because it should either read it as a parse error node and give nothing, or a message send node and complete without giving a DNU

**Comment by myroslavarm** [comment]
PR that fixes the DNU: https://github.com/pharo-project/pharo/pull/4175
question to explore: why was array node triggered in this case and what to do

**Comment by myroslavarm** [comment]
the DNU is fixed, so i'm closing this, but i opened another issue to reference the incorrect parsing
