### ISSUE TITLE
clean up

### ISSUE THREAD

**Issue by myroslavarm** [myroslavarm/Experimental-Completion#77]
get rid of unnecessary code, of all the old NEC stuff that's not used anymore
rename methods and classes so their names would make more sense

**Comment by myroslavarm** [comment]
step 1 : https://github.com/pharo-project/pharo/pull/4330
but there needs to be another PR where we remove old code before i close this
@MarcusDenker

**Comment by MarcusDenker** [comment]
I think this can be closed
