### ISSUE TITLE
#completionEntries should produce Entries, not symbols

### ISSUE THREAD

**Issue by myroslavarm** [myroslavarm/Experimental-Completion#80]
check backlog for reference

**Comment by MarcusDenker** [comment]
- CompletionEntry: we do the wrapping too late. when we instantiate it we just have symbols, so we do not know what they
   where originally (variable, selectors...)
   
   Thus: create entries in the #completionEntries method as described in issue #83

**Comment by MarcusDenker** [comment]
I can not rename the issue: the title should be "#completionEntries should...  "

**Comment by MarcusDenker** [comment]
https://github.com/pharo-project/pharo/pull/5135

**Comment by MarcusDenker** [comment]
https://github.com/pharo-project/pharo/pull/5206

**Comment by MarcusDenker** [comment]
merged

**Comment by myroslavarm** [comment]
@MarcusDenker i think this is ok to close now?

**Comment by MarcusDenker** [comment]
yes! (I can not close it, I can only close the ones that i created)
